data/plugins/redmine_message_customize/config/routes.rb
Rails.application.routes.draw do
  resources :custom_message_settings, only: [] do
    get  :edit,             on: :collection
    get  :default_messages, on: :collection
    post :update,           on: :collection
    post :toggle_enabled,   on: :collection
  end
end

data/plugins/redmine_message_customize/app/models/custom_message_setting.rb
class CustomMessageSetting < Setting
  validate :convertible_to_yaml,
           :custom_message_languages_are_available, :custom_message_keys_are_available

  def self.find_or_default
    super('plugin_redmine_message_customize')
  end

  def enabled?
    self.value[:enabled] != 'false'
  end

  def custom_messages(lang=nil, check_enabled=false)
    return {} if check_enabled && !self.enabled?

    messages = raw_custom_messages
    messages = messages[lang.to_s] if lang.present?
    messages || {}
  end

  def custom_messages_with_timestamp(lang)
    messages = self.custom_messages(lang, true)
    messages.merge({'redmine_message_customize_timestamp' => self.try(:updated_on).to_i.to_s})
  end

  def latest_messages_applied?(lang)
    return true if self.new_record?

    redmine_message_customize_timestamp = I18n.backend.send(:translations)[:"#{lang}"]&.[](:redmine_message_customize_timestamp)
    redmine_message_customize_timestamp == self.updated_on.to_i.to_s
  end

  def custom_messages_to_flatten_hash(lang=nil)
    self.class.flatten_hash(custom_messages(lang))
  end

  def custom_messages_to_yaml
    messages = custom_messages
    if messages.is_a?(Hash)
      messages.present? ? YAML.dump(messages) : ''
    else
      raw_custom_messages
    end
  end

  def update_with_custom_messages(custom_messages, lang)
    value = CustomMessageSetting.nested_hash(custom_messages)
    original_custom_messages = self.custom_messages
    messages =
      if value.present?
        original_custom_messages.merge({lang => value})
      else
        original_custom_messages.delete(lang)
        original_custom_messages
      end

    self.custom_messages = messages
    self.save
  end

  def update_with_custom_messages_yaml(yaml)
    self.custom_messages = yaml
    self.save
  end

  def toggle_enabled!
    self.value = self.value.merge({enabled: (!self.enabled?).to_s})
    self.save
  end

  # { date: { formats: { defaults: '%m/%d/%Y'}}} to {'date.formats.defaults' => '%m/%d/%Y'}
  def self.flatten_hash(hash=nil)
    return hash unless hash.is_a?(Hash)

    hash.each_with_object({}) do |(key, value), content|
      next self.flatten_hash(value).each do |k, v|
        content[:"#{key}.#{k}"] = v
      end if value.is_a? Hash
      content[key] = value
    end
  end

  # {'date.formats.defaults' => '%m/%d/%Y'} to { date: { formats: { defaults: '%m/%d/%Y'}}}
  def self.nested_hash(hash=nil)
    new_hash = {}
    hash.each do |key, value|
      h = value
      key.to_s.split('.').reverse_each do |k|
        h = {k => h}
      end
      new_hash = new_hash.deep_merge(h)
    end
    new_hash
  end

  private

  def raw_custom_messages
    self.value[:custom_messages] || self.value['custom_messages']
  end

  def custom_messages=(messages)
    messages = YAML.load("#{messages}") unless messages.is_a?(Hash)
    self.value = self.value.merge({custom_messages: messages.presence || {}})
  rescue Psych::SyntaxError => e
    self.value = self.value.merge({custom_messages: messages})
  end

  def custom_message_keys_are_available
    return if errors.present?

    en_translation_hash = self.class.flatten_hash(MessageCustomize::Locale.available_messages('en'))
    custom_message_keys =
      custom_messages.values.each_with_object([]){|val, ar|
        ar.concat(self.class.flatten_hash(val).keys)
      }.uniq

    unused_keys = custom_message_keys.reject{|k| en_translation_hash.keys.include?(:"#{k}")}
    unusable_type_of_keys = (custom_message_keys - unused_keys).reject{|k| en_translation_hash[:"#{k}"].is_a?(String)}

    if unused_keys.present?
      errors.add(:base, "#{l(:error_unused_keys)} keys: [#{unused_keys.join(', ')}]")
    end
    if unusable_type_of_keys.present?
      errors.add(:base, "#{l(:error_unusable_type_of_keys)} keys: [#{unusable_type_of_keys.join(', ')}]")
    end
  end

  def custom_message_languages_are_available
    return if errors.present?

    unavailable_languages =
      custom_messages.keys.compact.reject do |language|
        MessageCustomize::Locale.available_locales.include?(language.to_sym)
      end
    if unavailable_languages.present?
      errors.add(:base, l(:error_unavailable_languages) + " [#{unavailable_languages.join(', ')}]")
    end
  end

  def convertible_to_yaml
    raw_messages = raw_custom_messages
    if raw_messages.present? && !raw_messages.is_a?(Hash)
      begin
        YAML.load("#{raw_messages}")
        errors.add(:base, l(:error_invalid_yaml_format))
      rescue Psych::SyntaxError => e
        errors.add(:base, "#{l(:error_invalid_yaml_format)} #{e.message}")
      end
    end
  end
end

data/plugins/redmine_message_customize/app/controllers/custom_message_settings_controller.rb
class CustomMessageSettingsController < ApplicationController
  layout 'admin'
  menu_item :custom_messages
  self.main_menu = false
  before_action :require_admin, :set_custom_message_setting, :set_lang
  require_sudo_mode :edit, :update, :toggle_enabled, :default_messages

  def edit
  end

  def default_messages
    @file_path = Rails.root.join('config', 'locales', "#{@lang}.yml")
  end

  def update
    if setting_params.key?(:custom_messages) || params[:tab] == 'normal'
      @setting.update_with_custom_messages(setting_params[:custom_messages].try(:to_unsafe_h).try(:to_hash) || {}, @lang)
    elsif setting_params.key?(:custom_messages_yaml)
      @setting.update_with_custom_messages_yaml(setting_params[:custom_messages_yaml])
    end

    if @setting.errors.blank?
      flash[:notice] = l(:notice_successful_update)
      redirect_to edit_custom_message_settings_path(tab: params[:tab], lang: @lang)
    else
      render :edit
    end

  # Catch an exception that occurs when the value field capacity is exceeded (ActiveRecord::ValueTooLong)
  rescue ActiveRecord::StatementInvalid
    render_error l(:error_value_too_long)
  end

  def toggle_enabled
    if @setting.toggle_enabled!
      flash[:notice] =
        @setting.enabled? ? l(:notice_enabled_customize) : l(:notice_disabled_customize)
      redirect_to edit_custom_message_settings_path
    else
      render :edit
    end
  end

  private

  def set_custom_message_setting
    @setting = CustomMessageSetting.find_or_default
  end

  def setting_params
    params.fetch(:settings, {})
  end

  def set_lang
    @lang =
      MessageCustomize::Locale.find_language(
        params[:lang].presence || @setting.custom_messages.keys.first || current_user_language
      )
  end
end

data/plugins/redmine_message_customize/app/helpers/custom_message_settings_helper.rb
module CustomMessageSettingsHelper
  def available_message_options(setting, lang)
    options = [['', '']] +
                CustomMessageSetting.flatten_hash(MessageCustomize::Locale.available_messages(lang))
                .select{|_k, v| v.is_a?(String)}
                .map{|k, v| ["#{k}: #{v}", k]}

    options_for_select(options, disabled: setting.custom_messages_to_flatten_hash(lang).keys)
  end

  def normal_mode_input_fields(setting, lang)
    return '' if setting.custom_messages.is_a?(String) || setting.custom_messages.blank?

    content = ActiveSupport::SafeBuffer.new
    custom_messages_hash = setting.custom_messages_to_flatten_hash(lang.to_s)
    custom_messages_hash.each do |k, v|
      content += content_tag(:p) do
        content_tag(:label, k) +
        text_field_tag("settings[custom_messages][#{k}]", v.to_s) +
        link_to_function(sprite_icon('del'), '$(this).closest("p").remove()', class: 'icon clear-key-link')
      end
    end
    content
  end

  def open_default_messages_window_link(lang)
    link_to sprite_icon('file', l(:label_default_messages)),
            default_messages_custom_message_settings_path(lang: lang),
            class: 'icon text-plain',
            onclick: "window.open(this.href,'redmine_message_customize_plugin-default_messages', 'height=800, width=500');return false;",
            id: 'default-messages-link'
  end
end

data/plugins/redmine_message_customize/app/views/custom_message_settings/_messages.html.erb
<div>
  <%= select_tag 'select-key', available_message_options(@setting, lang), id: 'key-selector' %>
  <span class='icon'><%= sprite_icon('help', l(:text_description_of_search_box)) %></span>
</div>
<br>
<div class='tabular'>
  <%= normal_mode_input_fields(@setting, lang) %>
</div>

<%= javascript_tag do %>
$(document).ready(function() {
  setSelect2();
});

// Fix a problem with focus not working in Redmine 5.0 or later.
// issue: https://github.com/select2/select2/issues/5993
$(document).on('select2:open', function() {
  document.querySelector('.select2-search__field').focus();
});

var currentSearchKeyword;
$('#key-selector').on('select2:select', function (e) {
  var key = e.params.data.id;
  var val = e.params.data.text;
  AddMessageInputField(key, val);
}).on('select2:closing', function (e) {
  currentSearchKeyword = $('.select2-search__field')[0].value;
}).on('select2:open', function (e) {
  setTimeout(function() {
    if (currentSearchKeyword){
      $('.select2-search__field').val(currentSearchKeyword).trigger('input');
    }
  }, 0);
});

function AddMessageInputField(key, val){
  if($('input[name="settings[custom_messages[' + key + ']]"]').length === 0){
    $('<p></p>').prependTo($('#edit-custom-messages .tabular'));
    $('<label>' + key + '</label><br>').appendTo($('#edit-custom-messages .tabular p:first'));
    $('<input>').attr({
      type: 'text',
      value: val.replace(/.*: /, ''),
      name: 'settings[custom_messages][' + key + ']'
    }).appendTo($('#edit-custom-messages .tabular p:first'));
    $('<a>').attr({
       class: 'icon clear-key-link',
       href: '#',
       onclick: '$(this).closest("p").remove(); return false;'
    }).html('<%= sprite_icon('del') %>').appendTo($('#edit-custom-messages .tabular p:first'));
    $('#key-selector').val('').change();
    $('#key-selector option[value="' + key + '"]').prop("disabled", true).change();
    setSelect2();
  }
}

function setSelect2(){
  $("#key-selector").select2({
    width: '100%',
    placeholder: '<%= l(:text_placeholder_choose_key) %>',
    templateResult: function(option) {
return $('<span class="key">' + option.id + ':</span> <span>' + option.text.replace(/.*: /, '') + '</span>');
    }
  });
}
<% end %>

data/plugins/redmine_message_customize/app/views/custom_message_settings/_normal_tab.html.erb
<%= form_tag custom_message_settings_path, method: :post do %>
  <%= hidden_field_tag :tab, 'normal' %>
  <label><%= l(:field_language) %>: </label>
  <%= select_tag 'lang', options_for_select(languages_options, @lang), include_blank: true, data: {remote: true, url: url_for(action: :edit)}, onchange: '$("#ajax-indicator").show();' %>
  <hr>

  <div id='edit-custom-messages'>
    <%= render 'custom_message_settings/messages', lang: @lang %>
  </div>
  <%= submit_tag l(:button_save) %>
<% end %>

data/plugins/redmine_message_customize/app/views/custom_message_settings/_yaml_tab.html.erb
<%= form_tag custom_message_settings_path, method: :post do %>
  <%= hidden_field_tag :tab, 'yaml' %>
  <div class='help-message wiki'>
    <p>
      <%= l(:text_help_for_input_format) %><br>
      <%= l(:text_for_your_reference, open_default_messages_window_link(@lang)).html_safe %>
    </p>
    <p><%= l(:text_placeholder_template_case) %></p>
    <pre><%= l(:text_placeholder_yaml_template) %></pre>
  </div>
  <%= text_area_tag 'settings[custom_messages_yaml]', @setting.custom_messages_to_yaml, rows: '30', style: 'width: 100%', placeholder: l(:text_placeholder_yaml_template) %>
  <%= submit_tag l(:button_save) %>
<% end %>

data/plugins/redmine_message_customize/app/views/custom_message_settings/default_messages.html.erb
<%= stylesheet_link_tag('default_messages', plugin: 'redmine_message_customize') %>
<h2><%= l(:label_default_messages) %>(<%= "config/locales/#{@lang}.yml" %>)</h2>

<label><%= l(:field_language) %>: </label>
<%= select_tag 'lang', options_for_select(languages_options, @lang), onchange: "window.location.replace('#{default_messages_custom_message_settings_path}?lang=' + this.value)" %>

<% if @file_path.exist? %>
  <div class="autoscroll">
    <table class="filecontent syntaxhl">
      <tbody>
      <% line_num = 1 %>
      <% syntax_highlight_lines(@file_path.basename.to_s, Redmine::CodesetUtil.to_utf8_by_setting(File.read(@file_path))).each do |line| %>
        <tr id="L<%= line_num %>">
          <th class="line-num">
            <a href="#L<%= line_num %>"><%= line_num %></a>
          </th>
          <td class="line-code">
            <pre><%= line.html_safe %></pre>
          </td>
        </tr>
        <% line_num += 1 %>
      <% end %>
      </tbody>
    </table>
  </div>
<% end %>

data/plugins/redmine_message_customize/app/views/custom_message_settings/edit.html.erb
<%= stylesheet_link_tag('custom_messages', plugin: 'redmine_message_customize') %>
<%= stylesheet_link_tag('select2.min', plugin: 'redmine_message_customize') %>
<%= javascript_include_tag('select2.min', plugin: 'redmine_message_customize') %>
<% unless @setting.enabled? %>
  <div class='flash warning'>
    <%= l(:text_disabled_customize) %>
  </div>
<% end %>

<div class='message-customize-menu contextual'>
  <%= link_to sprite_icon('settings', (@setting.enabled? ? l(:label_disable_customize) : l(:label_enable_customize))), toggle_enabled_custom_message_settings_path, method: :post, class: 'icon' %> /
  <%= open_default_messages_window_link(@lang) %>
</div>

<h2><%= l(:label_custom_messages) %></h2>

<% if @setting.errors.any? %>
  <%= error_messages_for(@setting) %>
<% end %>

<%= render_tabs (@setting.errors.any? ? [] : [{name: 'normal', partial: 'normal_tab', label: 'label_normal_tab'}]) + [{name: 'yaml', partial: 'yaml_tab', label: 'label_yaml_tab'}] %>

data/plugins/redmine_message_customize/app/views/custom_message_settings/edit.js.erb
$('#edit-custom-messages').html("<%= j (render 'custom_message_settings/messages', lang: @lang) %>");
$('#default-messages-link').replaceWith('<%= open_default_messages_window_link(@lang) %>')
setSelect2();
$('#ajax-indicator').hide();